In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import accuracy_score,confusion_matrix

import pickle
import json

# Step 1: Problem Statement

# Step 2: Data Gathering

In [2]:
df = pd.read_csv("bank-additional-full.csv",sep=";")
df

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           5191.0   no  
1           5191.0   no  
2           5191.0   no  
3           5191.0   no  
4           5191.0   no  
...            ...  ...  
41183       4963.6  yes  
41184       4963.6   no  
41185       4963.6   no  
41186       4963.6  yes  
41187       4963.6   no  

[41188 rows x 21 columns]

In [3]:
df["nr.employed"] = df["nr.employed"].apply(lambda x : x/100)
df

age          job  marital            education  default housing loan  \
0       56    housemaid  married             basic.4y       no      no   no   
1       57     services  married          high.school  unknown      no   no   
2       37     services  married          high.school       no     yes   no   
3       40       admin.  married             basic.6y       no      no   no   
4       56     services  married          high.school       no      no  yes   
...    ...          ...      ...                  ...      ...     ...  ...   
41183   73      retired  married  professional.course       no     yes   no   
41184   46  blue-collar  married  professional.course       no      no   no   
41185   56      retired  married    university.degree       no     yes   no   
41186   44   technician  married  professional.course       no      no   no   
41187   74      retired  married  professional.course       no     yes   no   

         contact month day_of_week  ...  campaign  pdays  previous  \
0      telephone   may         mon  ...         1    999         0   
1      telephone   may         mon  ...         1    999         0   
2      telephone   may         mon  ...         1    999         0   
3      telephone   may         mon  ...         1    999         0   
4      telephone   may         mon  ...         1    999         0   
...          ...   ...         ...  ...       ...    ...       ...   
41183   cellular   nov         fri  ...         1    999         0   
41184   cellular   nov         fri  ...         1    999         0   
41185   cellular   nov         fri  ...         2    999         0   
41186   cellular   nov         fri  ...         1    999         0   
41187   cellular   nov         fri  ...         3    999         1   

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0      nonexistent          1.1          93.994          -36.4      4.857   
1      nonexistent          1.1          93.994          -36.4      4.857   
2      nonexistent          1.1          93.994          -36.4      4.857   
3      nonexistent          1.1          93.994          -36.4      4.857   
4      nonexistent          1.1          93.994          -36.4      4.857   
...            ...          ...             ...            ...        ...   
41183  nonexistent         -1.1          94.767          -50.8      1.028   
41184  nonexistent         -1.1          94.767          -50.8      1.028   
41185  nonexistent         -1.1          94.767          -50.8      1.028   
41186  nonexistent         -1.1          94.767          -50.8      1.028   
41187      failure         -1.1          94.767          -50.8      1.028   

       nr.employed    y  
0           51.910   no  
1           51.910   no  
2           51.910   no  
3           51.910   no  
4           51.910   no  
...            ...  ...  
41183       49.636  yes  
41184       49.636   no  
41185       49.636   no  
41186       49.636  yes  
41187       49.636   no  

[41188 rows x 21 columns]

In [4]:
df.transpose()

0            1            2            3      \
age                      56           57           37           40   
job               housemaid     services     services       admin.   
marital             married      married      married      married   
education          basic.4y  high.school  high.school     basic.6y   
default                  no      unknown           no           no   
housing                  no           no          yes           no   
loan                     no           no           no           no   
contact           telephone    telephone    telephone    telephone   
month                   may          may          may          may   
day_of_week             mon          mon          mon          mon   
duration                261          149          226          151   
campaign                  1            1            1            1   
pdays                   999          999          999          999   
previous                  0            0            0            0   
poutcome        nonexistent  nonexistent  nonexistent  nonexistent   
emp.var.rate            1.1          1.1          1.1          1.1   
cons.price.idx       93.994       93.994       93.994       93.994   
cons.conf.idx         -36.4        -36.4        -36.4        -36.4   
euribor3m             4.857        4.857        4.857        4.857   
nr.employed           51.91        51.91        51.91        51.91   
y                        no           no           no           no   

                      4            5                    6            7      \
age                      56           45                   59           41   
job                services     services               admin.  blue-collar   
marital             married      married              married      married   
education       high.school     basic.9y  professional.course      unknown   
default                  no      unknown                   no      unknown   
housing                  no           no                   no           no   
loan                    yes           no                   no           no   
contact           telephone    telephone            telephone    telephone   
month                   may          may                  may          may   
day_of_week             mon          mon                  mon          mon   
duration                307          198                  139          217   
campaign                  1            1                    1            1   
pdays                   999          999                  999          999   
previous                  0            0                    0            0   
poutcome        nonexistent  nonexistent          nonexistent  nonexistent   
emp.var.rate            1.1          1.1                  1.1          1.1   
cons.price.idx       93.994       93.994               93.994       93.994   
cons.conf.idx         -36.4        -36.4                -36.4        -36.4   
euribor3m             4.857        4.857                4.857        4.857   
nr.employed           51.91        51.91                51.91        51.91   
y                        no           no                   no           no   

                              8            9      ...              41178  \
age                              24           25  ...                 62   
job                      technician     services  ...            retired   
marital                      single       single  ...            married   
education       professional.course  high.school  ...  university.degree   
default                          no           no  ...                 no   
housing                         yes          yes  ...                 no   
loan                             no           no  ...                 no   
contact                   telephone    telephone  ...           cellular   
month                           may          may  ...                nov   
day_

# Step 3: EDA [Exploratory Data Analysis]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [6]:
# check for missing values
df.isna().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [7]:
df["age"].unique()

array([56, 57, 37, 40, 45, 59, 41, 24, 25, 29, 35, 54, 46, 50, 39, 30, 55,
       49, 34, 52, 58, 32, 38, 44, 42, 60, 53, 47, 51, 48, 33, 31, 43, 36,
       28, 27, 26, 22, 23, 20, 21, 61, 19, 18, 70, 66, 76, 67, 73, 88, 95,
       77, 68, 75, 63, 80, 62, 65, 72, 82, 64, 71, 69, 78, 85, 79, 83, 81,
       74, 17, 87, 91, 86, 98, 94, 84, 92, 89], dtype=int64)

In [8]:
print(df["duration"].unique())
for index,i in enumerate(df["duration"].unique()):
    if i <= 0:
        print(f"Index position {index} and value {i}")

[ 261  149  226 ... 1246 1556 1868]
Index position 939 and value 0


In [9]:
df["campaign"].unique()      

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 19, 18, 23, 14,
       22, 25, 16, 17, 15, 20, 56, 39, 35, 42, 28, 26, 27, 32, 21, 24, 29,
       31, 30, 41, 37, 40, 33, 34, 43], dtype=int64)

In [10]:
df["pdays"].unique()  

array([999,   6,   4,   3,   5,   1,   0,  10,   7,   8,   9,  11,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27,
        20], dtype=int64)

In [11]:
df["previous"].unique()

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [12]:
df["emp.var.rate"].unique()

array([ 1.1,  1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3. , -1.7, -1.1])

In [13]:
df["cons.price.idx"].unique()

array([93.994, 94.465, 93.918, 93.444, 93.798, 93.2  , 92.756, 92.843,
       93.075, 92.893, 92.963, 92.469, 92.201, 92.379, 92.431, 92.649,
       92.713, 93.369, 93.749, 93.876, 94.055, 94.215, 94.027, 94.199,
       94.601, 94.767])

In [14]:
df["cons.conf.idx"].unique()

array([-36.4, -41.8, -42.7, -36.1, -40.4, -42. , -45.9, -50. , -47.1,
       -46.2, -40.8, -33.6, -31.4, -29.8, -26.9, -30.1, -33. , -34.8,
       -34.6, -40. , -39.8, -40.3, -38.3, -37.5, -49.5, -50.8])

In [15]:
df["euribor3m"].unique()

array([4.857, 4.856, 4.855, 4.859, 4.86 , 4.858, 4.864, 4.865, 4.866,
       4.967, 4.961, 4.959, 4.958, 4.96 , 4.962, 4.955, 4.947, 4.956,
       4.966, 4.963, 4.957, 4.968, 4.97 , 4.965, 4.964, 5.045, 5.   ,
       4.936, 4.921, 4.918, 4.912, 4.827, 4.794, 4.76 , 4.733, 4.7  ,
       4.663, 4.592, 4.474, 4.406, 4.343, 4.286, 4.245, 4.223, 4.191,
       4.153, 4.12 , 4.076, 4.021, 3.901, 3.879, 3.853, 3.816, 3.743,
       3.669, 3.563, 3.488, 3.428, 3.329, 3.282, 3.053, 1.811, 1.799,
       1.778, 1.757, 1.726, 1.703, 1.687, 1.663, 1.65 , 1.64 , 1.629,
       1.614, 1.602, 1.584, 1.574, 1.56 , 1.556, 1.548, 1.538, 1.531,
       1.52 , 1.51 , 1.498, 1.483, 1.479, 1.466, 1.453, 1.445, 1.435,
       1.423, 1.415, 1.41 , 1.405, 1.406, 1.4  , 1.392, 1.384, 1.372,
       1.365, 1.354, 1.344, 1.334, 1.327, 1.313, 1.299, 1.291, 1.281,
       1.266, 1.25 , 1.244, 1.259, 1.264, 1.27 , 1.262, 1.26 , 1.268,
       1.286, 1.252, 1.235, 1.224, 1.215, 1.206, 1.099, 1.085, 1.072,
       1.059, 1.048,

In [16]:
df["nr.employed"].unique()

array([51.91 , 52.281, 51.958, 51.763, 50.991, 50.762, 50.175, 50.235,
       50.087, 49.916, 49.636])

In [17]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [18]:
for i in df.columns:
    print("Column Name:",i)
    print("Unique Values:\n",df[i].unique())
    print("Count of unique values:\n",df[i].value_counts())
    print()

Column Name: age
Unique Values:
 [56 57 37 40 45 59 41 24 25 29 35 54 46 50 39 30 55 49 34 52 58 32 38 44
 42 60 53 47 51 48 33 31 43 36 28 27 26 22 23 20 21 61 19 18 70 66 76 67
 73 88 95 77 68 75 63 80 62 65 72 82 64 71 69 78 85 79 83 81 74 17 87 91
 86 98 94 84 92 89]
Count of unique values:
 31    1947
32    1846
33    1833
36    1780
35    1759
      ... 
89       2
91       2
94       1
87       1
95       1
Name: age, Length: 78, dtype: int64

Column Name: job
Unique Values:
 ['housemaid' 'services' 'admin.' 'blue-collar' 'technician' 'retired'
 'management' 'unemployed' 'self-employed' 'unknown' 'entrepreneur'
 'student']
Count of unique values:
 admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: job, dtype: int64

Column Name: marital
Unique Values:


In [19]:
# Outliers 

In [20]:
# Assumptions 

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [22]:
##Labelling:

In [23]:
df.transpose()

0            1            2            3      \
age                      56           57           37           40   
job               housemaid     services     services       admin.   
marital             married      married      married      married   
education          basic.4y  high.school  high.school     basic.6y   
default                  no      unknown           no           no   
housing                  no           no          yes           no   
loan                     no           no           no           no   
contact           telephone    telephone    telephone    telephone   
month                   may          may          may          may   
day_of_week             mon          mon          mon          mon   
duration                261          149          226          151   
campaign                  1            1            1            1   
pdays                   999          999          999          999   
previous                  0            0            0            0   
poutcome        nonexistent  nonexistent  nonexistent  nonexistent   
emp.var.rate            1.1          1.1          1.1          1.1   
cons.price.idx       93.994       93.994       93.994       93.994   
cons.conf.idx         -36.4        -36.4        -36.4        -36.4   
euribor3m             4.857        4.857        4.857        4.857   
nr.employed           51.91        51.91        51.91        51.91   
y                        no           no           no           no   

                      4            5                    6            7      \
age                      56           45                   59           41   
job                services     services               admin.  blue-collar   
marital             married      married              married      married   
education       high.school     basic.9y  professional.course      unknown   
default                  no      unknown                   no      unknown   
housing                  no           no                   no           no   
loan                    yes           no                   no           no   
contact           telephone    telephone            telephone    telephone   
month                   may          may                  may          may   
day_of_week             mon          mon                  mon          mon   
duration                307          198                  139          217   
campaign                  1            1                    1            1   
pdays                   999          999                  999          999   
previous                  0            0                    0            0   
poutcome        nonexistent  nonexistent          nonexistent  nonexistent   
emp.var.rate            1.1          1.1                  1.1          1.1   
cons.price.idx       93.994       93.994               93.994       93.994   
cons.conf.idx         -36.4        -36.4                -36.4        -36.4   
euribor3m             4.857        4.857                4.857        4.857   
nr.employed           51.91        51.91                51.91        51.91   
y                        no           no                   no           no   

                              8            9      ...              41178  \
age                              24           25  ...                 62   
job                      technician     services  ...            retired   
marital                      single       single  ...            married   
education       professional.course  high.school  ...  university.degree   
default                          no           no  ...                 no   
housing                         yes          yes  ...                 no   
loan                             no           no  ...                 no   
contact                   telephone    telephone  ...           cellular   
month                           may          may  ...                nov   
day_

In [24]:
colnames_obj = df.select_dtypes(include="object").columns
print(colnames_obj)

##convert to dict all:

for i in colnames_obj:
    print("Col Name:",i)
    mydict = df[i].value_counts().to_dict()
    print(mydict)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'y'],
      dtype='object')
Col Name: job
{'admin.': 10422, 'blue-collar': 9254, 'technician': 6743, 'services': 3969, 'management': 2924, 'retired': 1720, 'entrepreneur': 1456, 'self-employed': 1421, 'housemaid': 1060, 'unemployed': 1014, 'student': 875, 'unknown': 330}
Col Name: marital
{'married': 24928, 'single': 11568, 'divorced': 4612, 'unknown': 80}
Col Name: education
{'university.degree': 12168, 'high.school': 9515, 'basic.9y': 6045, 'professional.course': 5243, 'basic.4y': 4176, 'basic.6y': 2292, 'unknown': 1731, 'illiterate': 18}
Col Name: default
{'no': 32588, 'unknown': 8597, 'yes': 3}
Col Name: housing
{'yes': 21576, 'no': 18622, 'unknown': 990}
Col Name: loan
{'no': 33950, 'yes': 6248, 'unknown': 990}
Col Name: contact
{'cellular': 26144, 'telephone': 15044}
Col Name: month
{'may': 13769, 'jul': 7174, 'aug': 6178, 'jun': 5318, 'nov': 4101, 'apr': 2632

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [27]:
## OHE:
mylist = ["job","marital","contact","month","day_of_week"]


# df = pd.get_dummies(df, columns=['body-style'])

for i in mylist:
    df = pd.get_dummies(df, columns=[i])

In [28]:
##labelling:
# Default: has credit in default?  

label_list = ["education","default"]

education_dict = {'university.degree': 7, 
                  'high.school': 5, 
                  'basic.9y': 4, 
                  'professional.course': 6, 
                  'basic.4y': 2, 
                  'basic.6y': 3, 
                  'unknown': 1, 
                  'illiterate': 0}

df["education"].replace(education_dict, inplace=True)


default_dict = {'no': 3, 'unknown': 2, 'yes': 1}
df["default"].replace(default_dict, inplace=True)

housing_dict={'yes': 3, 'no': 1, 'unknown': 2}
df["housing"].replace(housing_dict, inplace=True)

loan_dict={'yes': 3, 'no': 1, 'unknown': 2}
df["loan"].replace(loan_dict, inplace=True)


poutcome_dict= {'nonexistent': 2, 'failure': 3, 'success': 1}
df["poutcome"].replace(poutcome_dict, inplace=True)

y_dict={'no': 0, 'yes': 1}
df["y"].replace(y_dict, inplace=True)

In [29]:
df

age  education  default  housing  loan  duration  campaign  pdays  \
0       56          2        3        1     1       261         1    999   
1       57          5        2        1     1       149         1    999   
2       37          5        3        3     1       226         1    999   
3       40          3        3        1     1       151         1    999   
4       56          5        3        1     3       307         1    999   
...    ...        ...      ...      ...   ...       ...       ...    ...   
41183   73          6        3        3     1       334         1    999   
41184   46          6        3        1     1       383         1    999   
41185   56          7        3        3     1       189         2    999   
41186   44          6        3        1     1       442         1    999   
41187   74          6        3        3     1       239         3    999   

       previous  poutcome  ...  month_mar  month_may  month_nov  month_oct  \
0             0         2  ...          0          1          0          0   
1             0         2  ...          0          1          0          0   
2             0         2  ...          0          1          0          0   
3             0         2  ...          0          1          0          0   
4             0         2  ...          0          1          0          0   
...         ...       ...  ...        ...        ...        ...        ...   
41183         0         2  ...          0          0          1          0   
41184         0         2  ...          0          0          1          0   
41185         0         2  ...          0          0          1          0   
41186         0         2  ...          0          0          1          0   
41187         1         3  ...          0          0          1          0   

       month_sep  day_of_week_fri  day_of_week_mon  day_of_week_thu  \
0              0                0                1                0   
1              0                0                1                0   
2              0                0                1                0   
3              0                0                1                0   
4              0                0                1                0   
...          ...              ...              ...              ...   
41183          0                1                0                0   
41184          0                1                0                0   
41185          0                1                0                0   
41186          0                1                0                0   
41187          0                1                0                0   

       day_of_week_tue  day_of_week_wed  
0                    0                0  
1                    0                0  
2                    0                0  
3                    0                0  
4                    0                0  
...                ...              ...  
41183                0                0  
41184                0                0  
41185                0                0  
41186                0                0  
41187                0                0  

[41188 rows x 49 columns]

In [30]:
df.transpose()

0        1        2        3        4        5      \
age                 56.000   57.000   37.000   40.000   56.000   45.000   
education            2.000    5.000    5.000    3.000    5.000    4.000   
default              3.000    2.000    3.000    3.000    3.000    2.000   
housing              1.000    1.000    3.000    1.000    1.000    1.000   
loan                 1.000    1.000    1.000    1.000    3.000    1.000   
duration           261.000  149.000  226.000  151.000  307.000  198.000   
campaign             1.000    1.000    1.000    1.000    1.000    1.000   
pdays              999.000  999.000  999.000  999.000  999.000  999.000   
previous             0.000    0.000    0.000    0.000    0.000    0.000   
poutcome             2.000    2.000    2.000    2.000    2.000    2.000   
emp.var.rate         1.100    1.100    1.100    1.100    1.100    1.100   
cons.price.idx      93.994   93.994   93.994   93.994   93.994   93.994   
cons.conf.idx      -36.400  -36.400  -36.400  -36.400  -36.400  -36.400   
euribor3m            4.857    4.857    4.857    4.857    4.857    4.857   
nr.employed         51.910   51.910   51.910   51.910   51.910   51.910   
y                    0.000    0.000    0.000    0.000    0.000    0.000   
job_admin.           0.000    0.000    0.000    1.000    0.000    0.000   
job_blue-collar      0.000    0.000    0.000    0.000    0.000    0.000   
job_entrepreneur     0.000    0.000    0.000    0.000    0.000    0.000   
job_housemaid        1.000    0.000    0.000    0.000    0.000    0.000   
job_management       0.000    0.000    0.000    0.000    0.000    0.000   
job_retired          0.000    0.000    0.000    0.000    0.000    0.000   
job_self-employed    0.000    0.000    0.000    0.000    0.000    0.000   
job_services         0.000    1.000    1.000    0.000    1.000    1.000   
job_student          0.000    0.000    0.000    0.000    0.000    0.000   
job_technician       0.000    0.000    0.000    0.000    0.000    0.000   
job_unemployed       0.000    0.000    0.000    0.000    0.000    0.000   
job_unknown          0.000    0.000    0.000    0.000    0.000    0.000   
marital_divorced     0.000    0.000    0.000    0.000    0.000    0.000   
marital_married      1.000    1.000    1.000    1.000    1.000    1.000   
marital_single       0.000    0.000    0.000    0.000    0.000    0.000   
marital_unknown      0.000    0.000    0.000    0.000    0.000    0.000   
contact_cellular     0.000    0.000    0.000    0.000    0.000    0.000   
contact_telephone    1.000    1.000    1.000    1.000    1.000    1.000   
month_apr            0.000    0.000    0.000    0.000    0.000    0.000   
month_aug            0.000    0.000    0.000    0.000    0.000    0.000   
month_dec            0.000    0.000    0.000    0.000    0.000    0.000   
month_jul            0.000    0.000    0.000    0.000    0.000    0.000   
month_jun            0.000    0.000    0.000    0.000    0.000    0.000   
month_mar            0.000    0.000    0.000    0.000    0.000    0.000   
month_may            1.000    1.000    1.000    1.000    1.000    1.000   
month_nov            0.000    0.000    0.000    0.000    0.000    0.000   
month_oct            0.000    0.000    0.000    0.000    0.000    0.000   
month_sep            0.000    0.000    0.000    0.000    0.000    0.000   
day_of_week_fri      0.000    0.000    0.000    0.000    0.000    0.000   
day_of_week_mon      1.000    1.000    1.000    1.000    1.000    1.000   
day_of_week_thu      0.000    0.000    0.000    0.000    0.000    0.000   
day_of_week_tue      0.000    0.000    0.000    0.000    0.000    0.000   
day_of_week_wed      0.000    0.000    0.000    0.000    0.000    0.000   

                     6        7        8        9      ...    41178    41179  \
age                 59.000   41.000   24.000   25.000  ...   62.000   64.000   
education            6.000    1.000    6.000    5.000  ...    7.000    6.000   
default              3.000    

In [31]:
df.corr() ##corr as input

age  education   default   housing      loan  \
age                1.000000  -0.184463 -0.164965 -0.001603 -0.007368   
education         -0.184463   1.000000  0.225031  0.021101  0.011141   
default           -0.164965   0.225031  1.000000  0.015815  0.003782   
housing           -0.001603   0.021101  0.015815  1.000000  0.044296   
loan              -0.007368   0.011141  0.003782  0.044296  1.000000   
duration          -0.000866  -0.016129  0.011794 -0.007658 -0.000916   
campaign           0.004594  -0.001560 -0.032825 -0.011010  0.005166   
pdays             -0.034369  -0.025417 -0.080062 -0.010551  0.000345   
previous           0.024365   0.020942  0.102416  0.021314 -0.001327   
poutcome          -0.019750  -0.006642  0.023417  0.011783  0.001511   
emp.var.rate      -0.000371  -0.041447 -0.203263 -0.060196  0.001849   
cons.price.idx     0.000857  -0.098447 -0.168073 -0.080504 -0.002430   
cons.conf.idx      0.129372   0.043447 -0.026522 -0.033845 -0.012025   
euribor3m          0.010767  -0.032482 -0.195336 -0.059277  0.000125   
nr.employed       -0.017725  -0.024262 -0.189845 -0.045862  0.003903   
y                  0.030399   0.035848  0.099352  0.011552 -0.004909   
job_admin.        -0.102584   0.308200  0.121372  0.009949  0.018103   
job_blue-collar   -0.024191  -0.466516 -0.176382 -0.015214 -0.004662   
job_entrepreneur   0.031213   0.027243  0.001008  0.004480 -0.005220   
job_housemaid      0.085403  -0.126326 -0.036796 -0.004205 -0.002134   
job_management     0.062040   0.163488  0.035507 -0.007936 -0.001096   
job_retired        0.440772  -0.111165 -0.010070 -0.001892 -0.006570   
job_self-employed -0.001356   0.076344  0.004843 -0.000393 -0.006484   
job_services      -0.065731  -0.055246 -0.017599 -0.004397  0.000392   
job_student       -0.199749  -0.044240  0.032609  0.004656  0.004771   
job_technician    -0.064383   0.197815  0.069124  0.010149 -0.007511   
job_unemployed    -0.004426   0.001262 -0.010481  0.008631 -0.001518   
job_unknown        0.047773  -0.097569 -0.055630 -0.001290  0.004121   
marital_divorced   0.166125   0.010352  0.025050 -0.001858 -0.004159   
marital_married    0.271266  -0.147211 -0.130593 -0.011385 -0.001926   
marital_single    -0.411703   0.152993  0.123703  0.014494  0.005102   
marital_unknown    0.001062  -0.001478  0.007742 -0.008248 -0.000910   
contact_cellular  -0.007021   0.112270  0.135238  0.082186  0.008556   
contact_telephone  0.007021  -0.112270 -0.135238 -0.082186 -0.008556   
month_apr          0.014285  -0.001216  0.049002  0.029543  0.000578   
month_aug          0.065309   0.146962  0.008261  0.025873 -0.003461   
month_dec          0.046563   0.006598  0.028816  0.007039  0.007289   
month_jul         -0.043563  -0.046732 -0.037551 -0.000878  0.013629   
month_jun         -0.009532  -0.037596 -0.050067 -0.054996 -0.004828   
month_mar          0.008390   0.025558  0.051178  0.013108 -0.004334   
month_may         -0.067523  -0.104590 -0.066952 -0.022383  0.001684   
month_nov          0.030045   0.068920  0.085652  0.032332 -0.006138   
month_oct          0.053008   0.012541  0.060199  0.003108 -0.008996   
month_sep          0.040889   0.015873  0.054710  0.006986 -0.001905   
day_of_week_fri    0.007148  -0.005831 -0.003981 -0.015536  0.007376   
day_of_week_mon    0.019027   0.010649 -0.007028  0.011706  0.005742   
day_of_week_thu   -0.021356   0.009991  0.005004  0.011844 -0.002671   
day_of_week_tue    0.019137  -0.011710 -0.003641 -0.010433 -0.008350   
day_of_week_wed   -0.023671  -0.003609  0.009592  0.001710 -0.002046   

                   duration  campaign     pdays  previous  poutcome  ...  \
age               -0.000866  0.004594 -0.034369  0.024365 -0.019750  ...   
education         -0.016129 -0.001560 -0.025417  0.020942 -0.006642  ...   
default            0.011794 -0.032825 -0.080062  0.102416  0.023417  ...   
housing           -0.007658 -0.011010 -0.010551  0.021314  0.011783  ...   
loan              -0.000916  0.005166  0.00

In [32]:
##only for corr with actual datasets
df1 = pd.read_csv("bank-additional-full.csv",sep=";")
df1.corr()

age  duration  campaign     pdays  previous  \
age             1.000000 -0.000866  0.004594 -0.034369  0.024365   
duration       -0.000866  1.000000 -0.071699 -0.047577  0.020640   
campaign        0.004594 -0.071699  1.000000  0.052584 -0.079141   
pdays          -0.034369 -0.047577  0.052584  1.000000 -0.587514   
previous        0.024365  0.020640 -0.079141 -0.587514  1.000000   
emp.var.rate   -0.000371 -0.027968  0.150754  0.271004 -0.420489   
cons.price.idx  0.000857  0.005312  0.127836  0.078889 -0.203130   
cons.conf.idx   0.129372 -0.008173 -0.013733 -0.091342 -0.050936   
euribor3m       0.010767 -0.032897  0.135133  0.296899 -0.454494   
nr.employed    -0.017725 -0.044703  0.144095  0.372605 -0.501333   

                emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
age                -0.000371        0.000857       0.129372   0.010767   
duration           -0.027968        0.005312      -0.008173  -0.032897   
campaign            0.150754        0.127836      -0.013733   0.135133   
pdays               0.271004        0.078889      -0.091342   0.296899   
previous           -0.420489       -0.203130      -0.050936  -0.454494   
emp.var.rate        1.000000        0.775334       0.196041   0.972245   
cons.price.idx      0.775334        1.000000       0.058986   0.688230   
cons.conf.idx       0.196041        0.058986       1.000000   0.277686   
euribor3m           0.972245        0.688230       0.277686   1.000000   
nr.employed         0.906970        0.522034       0.100513   0.945154   

                nr.employed  
age               -0.017725  
duration          -0.044703  
campaign           0.144095  
pdays              0.372605  
previous          -0.501333  
emp.var.rate       0.906970  
cons.price.idx     0.522034  
cons.conf.idx      0.100513  
euribor3m          0.945154  
nr.employed        1.000000

In [93]:
## kdeplots for int and float types:

# cols1 = df1.select_dtypes(include=["int","float"]).columns
# cols1
# for i in cols1:
#     print("Column Name:",i)
#     print(sns.kdeplot(x = df[i]))
#     plt.show()
#     print()

# Step 6. Model Training

In [34]:
x = df.drop('y', axis=1)
y = df['y']

x_train,x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=9)

In [35]:
x_train.shape,y_train.shape, x_test.shape, y_test.shape

((28831, 48), (28831,), (12357, 48), (12357,))

In [121]:
#model object

logistic_model = LogisticRegression(max_iter=300)

In [122]:
#fitting

logistic_model.fit(x_train,y_train)

C:\Users\nisha\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [123]:
##prediction

y_pred_logistic = logistic_model.predict(x_test)
y_pred_logistic.shape

(12357,)

In [124]:
print("Accuracy of logistic_model",accuracy_score(y_test,y_pred_logistic))
# 0.9073399692481994 @100iter
# 0.9104960750991341 @200iter
# 0.9108197782633325 @300iter

# 0.9123573682932751

Accuracy of logistic_model 0.9113053330096301


In [40]:
# Pickle file 

with open('model.pkl','wb') as file:
    pickle.dump(logistic_model,file)

In [41]:
# df1 = df.transpose()
# df1[[0]]

In [42]:
d1 = { "columns": ['age',
 'job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed'],
      
    "result_values":{'no': 0, 'yes': 1}
    
}
with open("asset.json","w") as file:
    json.dump(d1,file)

In [43]:
df.head(1).transpose()

0
age                 56.000
education            2.000
default              3.000
housing              1.000
loan                 1.000
duration           261.000
campaign             1.000
pdays              999.000
previous             0.000
poutcome             2.000
emp.var.rate         1.100
cons.price.idx      93.994
cons.conf.idx      -36.400
euribor3m            4.857
nr.employed         51.910
y                    0.000
job_admin.           0.000
job_blue-collar      0.000
job_entrepreneur     0.000
job_housemaid        1.000
job_management       0.000
job_retired          0.000
job_self-employed    0.000
job_services         0.000
job_student          0.000
job_technician       0.000
job_unemployed       0.000
job_unknown          0.000
marital_divorced     0.000
marital_married      1.000
marital_single       0.000
marital_unknown      0.000
contact_cellular     0.000
contact_telephone    1.000
month_apr            0.000
month_aug            0.000
month_dec            0.000
month_jul            0.000
month_jun            0.000
month_mar            0.000
month_may            1.000
month_nov            0.000
month_oct            0.000
month_sep            0.000
day_of_week_fri      0.000
day_of_week_mon      1.000
day_of_week_thu      0.000
day_of_week_tue      0.000
day_of_week_wed      0.000

## user test function

In [ ]:
User test func is based on 
x_test.shape, y_test.shape

In [116]:
sampledf.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [47]:
x_test.head(1).transpose()

35679
age                 25.000
education            5.000
default              3.000
housing              3.000
loan                 1.000
duration           432.000
campaign             3.000
pdays              999.000
previous             0.000
poutcome             2.000
emp.var.rate        -1.800
cons.price.idx      92.893
cons.conf.idx      -46.200
euribor3m            1.244
nr.employed         50.991
job_admin.           0.000
job_blue-collar      0.000
job_entrepreneur     0.000
job_housemaid        0.000
job_management       0.000
job_retired          0.000
job_self-employed    0.000
job_services         0.000
job_student          1.000
job_technician       0.000
job_unemployed       0.000
job_unknown          0.000
marital_divorced     0.000
marital_married      0.000
marital_single       1.000
marital_unknown      0.000
contact_cellular     1.000
contact_telephone    0.000
month_apr            0.000
month_aug            0.000
month_dec            0.000
month_jul            0.000
month_jun            0.000
month_mar            0.000
month_may            1.000
month_nov            0.000
month_oct            0.000
month_sep            0.000
day_of_week_fri      0.000
day_of_week_mon      1.000
day_of_week_thu      0.000
day_of_week_tue      0.000
day_of_week_wed      0.000

In [49]:
len(x_test.head(1).transpose()) ## we need 48 inputs

48

In [52]:
columns = {"Column Names":x_test.columns.tolist()}
print(columns)

{'Column Names': ['age', 'education', 'default', 'housing', 'loan', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired', 'job_self-employed', 'job_services', 'job_student', 'job_technician', 'job_unemployed', 'job_unknown', 'marital_divorced', 'marital_married', 'marital_single', 'marital_unknown', 'contact_cellular', 'contact_telephone', 'month_apr', 'month_aug', 'month_dec', 'month_jul', 'month_jun', 'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep', 'day_of_week_fri', 'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue', 'day_of_week_wed']}


In [53]:
## json format --make
with open('column_names.json',"w") as file:
    json.dump(columns,file)

In [60]:
## json format --open
with open('column_names.json',"r") as file:
    column_names = json.load(file)
column_names['Column Names'] ##access each cols

['age',
 'education',
 'default',
 'housing',
 'loan',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'emp.var.rate',
 'cons.price.idx',
 'cons.conf.idx',
 'euribor3m',
 'nr.employed',
 'job_admin.',
 'job_blue-collar',
 'job_entrepreneur',
 'job_housemaid',
 'job_management',
 'job_retired',
 'job_self-employed',
 'job_services',
 'job_student',
 'job_technician',
 'job_unemployed',
 'job_unknown',
 'marital_divorced',
 'marital_married',
 'marital_single',
 'marital_unknown',
 'contact_cellular',
 'contact_telephone',
 'month_apr',
 'month_aug',
 'month_dec',
 'month_jul',
 'month_jun',
 'month_mar',
 'month_may',
 'month_nov',
 'month_oct',
 'month_sep',
 'day_of_week_fri',
 'day_of_week_mon',
 'day_of_week_thu',
 'day_of_week_tue',
 'day_of_week_wed']

In [63]:
len(column_names['Column Names'])

48

In [62]:
user_input = np.zeros(len(column_names['Column Names']))
user_input

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
logistic_model.predict([user_input])  ##to chk if everything is ok // no error
## to chk shape is correct or not

C:\Users\nisha\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [96]:
encoded_data = {
    "education" : {'university.degree': 7, 
                  'high.school': 5, 
                  'basic.9y': 4, 
                  'professional.course': 6, 
                  'basic.4y': 2, 
                  'basic.6y': 3, 
                  'unknown': 1, 
                  'illiterate': 0},

        "default" : {'no': 3, 'unknown': 2, 'yes': 1},
        "housing":{'yes': 3, 'no': 1, 'unknown': 2},
        "loan":{'yes': 3, 'no': 1, 'unknown': 2},
        "poutcome":{'nonexistent': 2, 'failure': 3, 'success': 1}   
}

##json file --make
with open("encoded_data.json","w") as file:
    json.dump(encoded_data,file)

In [98]:
##json file --open
with open("encoded_data.json","r") as file:
    encoded_data = json.load(file)
print(encoded_data)

{'education': {'university.degree': 7, 'high.school': 5, 'basic.9y': 4, 'professional.course': 6, 'basic.4y': 2, 'basic.6y': 3, 'unknown': 1, 'illiterate': 0}, 'default': {'no': 3, 'unknown': 2, 'yes': 1}, 'housing': {'yes': 3, 'no': 1, 'unknown': 2}, 'loan': {'yes': 3, 'no': 1, 'unknown': 2}, 'poutcome': {'nonexistent': 2, 'failure': 3, 'success': 1}}


In [101]:
## check dict values 
encoded_data['education']['basic.4y']

2

In [113]:
age=56
job="housemaid"
marital= "married"
education= "basic.4y"
default="no"
housing="no"
loan="no"
contact="telephone"
month="may"
day_of_week="mon"
duration=261
campaign=1
pdays=999
previous=0
poutcome="nonexistent"
emp_var_rate=1.1
cons_price_idx=93.994
cons_conf_idx=-36.4
euribor3m=4.857
nr_employed=5191.0



user_input[0]= age

#giving values to OHE -->
##prefix is job_ 
search_str = "job_"+job   ##index name formatting
column_array = np.array(column_names['Column Names']) ##convert to arrays
index = np.where(column_array == search_str)  ##getting index pos
user_input[index]=1                          #setting value for job


search_str = "marital_"+marital   ##index name formatting
column_array = np.array(column_names['Column Names']) ##convert to arrays
index = np.where(column_array == search_str)  ##getting index pos
user_input[index]=1    


##educ:
user_input[3]= encoded_data['education'][education]
user_input[4]= encoded_data['default'][default]
user_input[5]= encoded_data['housing'][housing]
user_input[6]= encoded_data['loan'][loan]


search_str = "contact_"+contact   ##index name formatting
column_array = np.array(column_names['Column Names']) ##convert to arrays
index = np.where(column_array == search_str)  ##getting index pos
user_input[index]=1    
user_input

search_str = "month_"+month   ##index name formatting
column_array = np.array(column_names['Column Names']) ##convert to arrays
index = np.where(column_array == search_str)  ##getting index pos
user_input[index]=1    
user_input

search_str = "day_of_week_"+day_of_week   ##index name formatting
column_array = np.array(column_names['Column Names']) ##convert to arrays
index = np.where(column_array == search_str)  ##getting index pos
user_input[index]=1 
user_input

user_input[10] = duration
user_input[11] = campaign
user_input[12] = pdays
user_input[13] = previous
user_input[14] = encoded_data['poutcome'][poutcome]
user_input[15] = emp_var_rate
user_input[16] = cons_price_idx
user_input[17] = cons_conf_idx
user_input[18] = euribor3m
user_input[19] = nr_employed


[ 5.6000e+01  0.0000e+00  0.0000e+00  2.0000e+00  3.0000e+00  1.0000e+00
  1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
  0.0000e+00  0.0000e+00  2.0000e+00  1.1000e+00  9.3994e+01 -3.6400e+01
  4.8570e+00  5.1910e+03  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
  0.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00
  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00
  0.0000e+00  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00
  0.0000e+00  0.0000e+00  1.0000e+00  0.0000e+00  0.0000e+00  0.0000e+00]


In [ ]:
data = [[age,job,marital,education,default,housing,loan,
      contact,month,day_of_week,duration,campaign,pdays,
      previous,poutcome,emp_var_rate,cons_price_idx,
      cons_conf_idx,euribor3m,nr_employed]]


In [118]:
##output mapping of user inputs
print(f"{user_input=}")
print(len(user_input))

user_input=array([ 5.6000e+01,  0.0000e+00,  0.0000e+00,  2.0000e+00,  3.0000e+00,
        1.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.0000e+00,
        1.1000e+00,  9.3994e+01, -3.6400e+01,  4.8570e+00,  5.1910e+03,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
        0.0000e+00,  0.0000e+00,  0.0000e+00])
48


In [120]:
logistic_model.predict([user_input])

C:\Users\nisha\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [68]:
x_test.head(1).transpose()

35679
age                 25.000
education            5.000
default              3.000
housing              3.000
loan                 1.000
duration           432.000
campaign             3.000
pdays              999.000
previous             0.000
poutcome             2.000
emp.var.rate        -1.800
cons.price.idx      92.893
cons.conf.idx      -46.200
euribor3m            1.244
nr.employed         50.991
job_admin.           0.000
job_blue-collar      0.000
job_entrepreneur     0.000
job_housemaid        0.000
job_management       0.000
job_retired          0.000
job_self-employed    0.000
job_services         0.000
job_student          1.000
job_technician       0.000
job_unemployed       0.000
job_unknown          0.000
marital_divorced     0.000
marital_married      0.000
marital_single       1.000
marital_unknown      0.000
contact_cellular     1.000
contact_telephone    0.000
month_apr            0.000
month_aug            0.000
month_dec            0.000
month_jul            0.000
month_jun            0.000
month_mar            0.000
month_may            1.000
month_nov            0.000
month_oct            0.000
month_sep            0.000
day_of_week_fri      0.000
day_of_week_mon      1.000
day_of_week_thu      0.000
day_of_week_tue      0.000
day_of_week_wed      0.000

In [44]:
age = 
job = 
marital = 
education = 
default = 
housing = 
loan = 
contact = 
month = 
day_of_week = 
duration = 
campaign = 
pdays = 
previous = 
poutcome = 
emp.var.rate = 
cons.price.idx = 
cons.conf.idx = 
euribor3m = 

SyntaxError: invalid syntax (702804863.py, line 1)